### PR TITLE
Second TMX Overhaul, Part 2

### PR DESCRIPTION
**Pull request by TheRamenChef**
For part 1, see #232.

This pull request adds even more missing features, including:

  - All resources except spritesheets are now cached using URLs as keys (they still work with strings)
  - Resources can now be loaded asynchronously
  - Most entities loaded from map objects are now rendered as part of their respective layers
  - Tilesets that use individual images for each tile are now supported
  - Tile types are now supported
  - File custom properties are now supported, though only tentatively
  - Light sources now use an enum for their type
  - Various refinements for several features

This pull request was going to have an implementation of JSON maps, but I got stuck on the tile layer data. Actually removing 451348d from the branch proved to be too much of a hassle; if you can do it, go ahead, or don't.

### CODE REVIEW

**Comment by TheRamenChef** [comment]
For most of the changesm either a unit test would be infeasible (such as graphics changes) or the unit tests were already there (such as moving resource storage to URLs).

With regards to the layer entities, I didn't know that `IRenderable` wasn't required for drawing an entity; I will need to look into that and implement it for `AnimationController`s.

**Comment by steffen-wilke** [comment]
> For most of the changesm either a unit test would be infeasible (such as graphics changes) or the unit tests were already there (such as moving resource storage to URLs).

Okay, since this part was also just something additional from my side, I guess the topic of unit tests is done for this PR.

**Comment by TheRamenChef** [comment]
Looking at the code again, it looks like it was just the sorting optimization that was made. I've reverted that change.

Also, with entities bound to layers, it doesn't change the way it's rendered if you put the map object layer on the top, or bottom if you’re using the `BACKGROUND` render type.

**Comment by steffen-wilke** [comment]
I did some additions to the new feature of rendering `Entities` with their layers. From the code, this PR looks good now in my opinion. But when testing the branch with our game **DR.LEPUS**, the layers of the map don't seem to be rendered anymore. I did't find the reason for this yet, but I think once we've fixed that issue, we can merge this PR.

@TheRamenChef Are there any changes to the map format that would result in the engine version ofthis branch being incompatible with previous maps? Maybe you can also have a look at this.

**Comment by TheRamenChef** [comment]
I think I found the problem. Maps with these changes have a `finish` method that resolves external resources, among other things. This method would not be called for TMX resources from a `ResourceBundle`.

Does it work now?

**Pull request merged**
