### PR TITLE
Update to java 19

### PR DESCRIPTION
**Pull request by Gamebuster19901**
<s>No changes to the codebase are required.</s>

### CODE REVIEW

**Comment by Gamebuster19901** [comment]
Actually, Object.finalize() is deprecated and removed in jdk 18.

We should use Cleaners. I'll work on implementing this for the sound system.

**Comment by nightm4re94** [comment]
I wanted to give GraalVM CE a try for our builds. This might be a good opportunity to test that and migrate to Java 19 at the same time. Do you want to set up the [GraalVM action](https://github.com/graalvm/setup-graalvm) in our build workflows?

**Comment by Gamebuster19901** [comment]
> I wanted to give GraalVM CE a try for our builds. This might be a good opportunity to test that and migrate to Java 19 at the same time. Do you want to set up the [GraalVM action](https://github.com/graalvm/setup-graalvm) in our build workflows?

I've never worked with that software so I wouldn't really be comfortable making a PR for it.

**Comment by nightm4re94** [comment]
That's alright, then go ahead as planned 👍 thank you!

**Comment by Gamebuster19901** [comment]
This is pretty much done, just needs testing to make sure sounds play and that the resources are properly relinquished.

I'll try to test it by the end of the week, been feeling sick lately.

**Comment by nightm4re94** [comment]
Swift recovery to you then and thanks already 😊

**Comment by steffen-wilke** [comment]
I've just tested this PR and it seems that sounds are not played anymore with these changes.
Reproduced with utiLITI by adding a `Sound source` and playing it directly within the editor.

**Comment by steffen-wilke** [comment]
Other than that: we had a quick discussion today about Java 19 and what it brings for us and we'd really like to give [Project: Panama](https://openjdk.org/projects/panama/) a try to approach our native dependencies differently. This could give us the opportunity to replace JNI for input and sound.

**Comment by nightm4re94** [comment]
> I've just tested this PR and it seems that sounds are not played anymore with these changes. Reproduced with utiLITI by adding a `Sound source` and playing it directly within the editor.

Can confirm. Not only does playing sounds not work, it also crashed my entire PC without error messages.

**Comment by Gamebuster19901** [comment]
> Can confirm. Not only does playing sounds not work, it also crashed my entire PC without error messages.

Yikes, I'll take a look

**Comment by Gamebuster19901** [comment]
I'm unable to reproduce this when manually playing a sound:

```java
try {
	Game.audio().playSound(new Sound(new BufferedInputStream(new FileInputStream(new File("/home/gamebuster/Desktop/dolphinDump/Audio/example.mp3"))), "test"));
} catch (IOException | UnsupportedAudioFileException e) {
	e.printStackTrace();
}
```

However, I am unable to add sounds at all using the editor, the dropdown doesn't show imported sounds.

**Comment by steffen-wilke** [comment]
> However, I am unable to add sounds at all using the editor, the dropdown doesn't show imported sounds.

I fixed this yesterday with #772

**Comment by Gamebuster19901** [comment]
I'm still unable to reproduce this issue.

https://www.youtube.com/watch?v=1eYYqMb2Fw0

**Comment by nightm4re94** [comment]
Really appreciate the effort, thank you!
I've rebased your branch onto master for testing.
When I play a sound, a thread is spawned for the playback, I can't hear anything, and the thread is never closed. (The sound used in the examples below is only around one second long)
image
image
Each new playback results in around 20% increased CPU load:
image

**Comment by nightm4re94** [comment]
[Sounds.zip](https://github.com/gurkenlabs/litiengine/files/10327465/Sounds.zip)
These are two of the sounds I tried using (.ogg and .wav).

**Comment by steffen-wilke** [comment]
Maybe a Windows thing? Gesendet von Outlook für Android

**Comment by Gamebuster19901** [comment]
I'll try those out, I only used a .mp4 previously.

**Comment by Gamebuster19901** [comment]
Also, if you don't mind, can you two post a debug crash output? (press CTRL+ALT+SHIFT+C)

**Comment by Gamebuster19901** [comment]
Issue fixed, ready for review.

**Comment by Gamebuster19901** [comment]
Actually there are a few more minor issues I need to fix

**Review by nightm4re94 — APPROVED** [review]
Thanks a lot! We needed a bit of a break after the game jam, as usual :P

**Pull request merged**
