### PR TITLE
Use URL fragments for external resources

### PR DESCRIPTION
**Pull request by TheRamenChef**
This is an addition to #272.

This pull request aims to resolve what would otherwise become an edit war on image layer rendering. Among other things, it changes the implementation of `ResourceBundle`s to use URL fragments to reference internal images. It's somewhat backwards-compatible, but older bundles may experience problems.

Additionally, this pull request removes the unused `path` property from maps, and the improper `Comparable` implementation from resources. The `Comparable` implementation has been moved to a `Comparator` in the same interface called `BY_NAME`.

### CODE REVIEW

**Comment by steffen-wilke** [comment]
Just checked out this PR. What would be the steps to migrate a `.litidata` file to the new format? Right now, I can't open up any of our `ResourceBundles` in the utiLITI anymore. I'd like to add a step-by-step explanation on how to migrate in the patch notes of the new version release.

Could you maybe provide a PR for the [Gurk Nukem](https://github.com/gurkenlabs/litiengine-gurk-nukem) example game to fix its `ResourceBundle` so that it can be loaded in the editor again?

**Comment by TheRamenChef** [comment]
The only steps I could think of don't apply for that example. Was there a crash report?

**Comment by steffen-wilke** [comment]
Here are all the exceptions that were thrown.

[crash.txt](https://github.com/gurkenlabs/litiengine/files/3292347/crash.txt)

**Comment by TheRamenChef** [comment]
I configured it to warn when there's an extension as well.

https://github.com/gurkenlabs/litiengine-gurk-nukem/pull/2

Tell me if there are still errors.

For migration, you need to change internal references in the `.litidata` file like `tileset.tsx` to `#tileset`.

**Comment by steffen-wilke** [comment]
Thanks.

Is this format compatible with tiled? Or would this result in pretty much unusable maps if you re-export them e.g. using the "Synchronize Maps" functionality in utiLITI?

**Comment by TheRamenChef** [comment]
I didn't know that functionality existed. It probably wouldn't work, at least not with the current state of this PR.

**Comment by steffen-wilke** [comment]
I'd say that we decouple this PR from the `utiliti_cleanup` branch which is in a working state and could right now be merged to the master branch. When we fixed the rest of the loose ends here we could then just merge it directly to the master branch.

**Comment by TheRamenChef** [comment]
Probably not in the current branch.

**Pull request closed without merging**
