### PR TITLE
JavaFX Video Player

### PR DESCRIPTION
**Pull request by Gamebuster19901**
I've been working on #291 using JavaFX.

As a result I had to make some changes to how LitiEngine is compiled.

If you're compiling using a JDK older than JDK11, then JavaFX must exist on the system classpath. Some JDKs older than JDK11 come with JavaFX, but some don't (most notably openjdk8). If yours doesn't you will have to upgrade to Java 11 or install OpenJFX onto your system manually.

If you're compiling with JDK11 or newer, then you don't have to do anything. Gradle will automatically add it to the build path. 

Using gradle to add JavaFX to the build path is not possible with JDKs older than JDK11, as the OpenJFX gradle plugin required to install it is only compatible with Java 11 or higher. If you attempt to use it on an older version of Java, you will get an UnsupportedClassVersionError upon building the project.

Travis will now build LitiEngine using both Java 8 and Java 11 to ensure it can run on both.

<h2>TODO</h2>

- [x] Add JavaFX to classpath
- [x] Travis builds with both Java 8 and Java 11
- [x] Implement a VideoPlayer which is a GuiComponent 
- [x] Implement VideoRenderer to render the GuiComponent
- [ ] Add tests

### CODE REVIEW

**Comment by Gamebuster19901** [comment]
Obviously the build will fail as the build server is using openjdk 8, which does not have openjfx. OpenJDK 8 will never include OpenJFX. See https://github.com/AdoptOpenJDK/openjdk-build/issues/577

**Comment by Gamebuster19901** [comment]
Merge conflicts are now resolved.

VideoRenderer still needs to be implemented. I'm not knowledgeable enough with the internals of LitiEngine to do it myself.

I'm currently rendering on the screen using

```java
    @Override
    public void render(Graphics2D g) {
      video.getPanel().paint(g);
    }
```

This is what it looks like (the video is low definition, [here](https://www.youtube.com/watch?time_continue=1&v=B3S6uebE-1M&feature=emb_logo) is the original for comparison)

image

**Comment by Gamebuster19901** [comment]
This PR is ready for review

**Comment by nightm4re94** [comment]
Thank you for the remarkable work you've done here! It's really nice to see major features being tackled by the community.
We are currently reviewing this PR, yet I want to share some thoughts already:
While the implementation of video Resource management and the overall execution seems fine so far, having picked JavaFX for the solution to our problem kind of contradicts fundamental design principles of LITIengine.
Referencing an external framework is by itself something we want to avoid as much as possible, but in this case we are dealing with a framework that provides alternatives to other LITIengine features. If we use JavaFX for a video player, why stop there? Why not port LITIengine's entiere rendering pipeline to JFX? Why not the GUI framework as well? With JFX no longer being an official part of Java, I think we need to consider referencing it very carefully, as the answer to the above questions would be "because LITIengine is a 2D Java game engine based on AWT".
Had we picked JavaFX right from the get-go as we began implementing LITIengine, it would've been an absolutely feasible (and yes, in many regards superior to AWT) choice for rendering and UI. However, we did not. We also do not possess the capacities to port LITIengine to JavaFX within a resonable amount of time. At this point I think AWT has become our trademark for simplicity, steadiness, and learnability. There are plenty of JFX alternatives for game development out there, but the lack of alternatives based on AWT also gives us an advantage in the market, I think.

How do you feel about this? What possible alternatives to a JavaFX panel did you find during your research?

**Comment by Gamebuster19901** [comment]
The reason I selected JavaFX is because there are simply are no other java video libraries that are under active development and are compatible with LitiEngine's license.

[Xuggler](https://github.com/artclarke/xuggle-xuggler) has a compatible license (LGPL) but hasn't been updated in 6 years
[Humble-Video](https://github.com/artclarke/humble-video) is AGPL so is not compatible
[VLCJ](https://github.com/caprica/vlcj) is GPL so is not compatible

I also tried using [VLC's remote control interface](https://wiki.videolan.org/documentation:modules/rc/) but I wasn't able to figure out how to stream the video output the java process.

I suppose the most promising alternative is [ffmpeg-cli-wrapper](https://github.com/bramp/ffmpeg-cli-wrapper) which is BSD but it hasn't had a new release in ~ 3 years. The latest commit to the repo was 2 years ago, excluding the one they just pushed 3 hours ago. I thought the project was dead up until the point I started typing this.

**Comment by nightm4re94** [comment]
Thanks for the suggestions, I'll update the original issue with a list of options.
I'm sure we can find a fitting alternative together ;)

**Comment by Gamebuster19901** [comment]
There's also a possibility of not including this with LitiEngine itself but instead making it a separate 'plugin' of sorts.

**Comment by nightm4re94** [comment]
I agree, but I'd prefer an out-of-the-box approach here. 
Updated #291 with an overview of potentially useful frameworks.

**Comment by nightm4re94** [comment]
Can I suggest splitting this up into two separate PRs?
- One for video resource management (which seems to be nearly complete here)
- One for video playback as discussed in #291

**Pull request closed without merging**
