### PR TITLE
Emitter panel revision

### LINKED ISSUE #298: Fix Emitter editing
Currently, the dialog that allows editing emitters in the utiLITI editor has some major issues:

image

* UI-wise the elements are misaligned and some are not fully readable (see screenshot) this makes the UI hard to use and understand
* When trying to create a new emitter from scratch in the editor, this doesn't seem to be possible at the moment; at least I wasn't able to get a visible result.
  * Some investigations showed, that a lot of `ParticleParameters` are not serialized properly (maybe unchanged values, especially the max values are not set as custom property?)
* I would say that this feature is **entirely broken** right now, unless you have an already working emitter and just want to tweak some numbers.
* When adding a new emitter, we should define appropriate default values so the user can already see something

image

We might also think about integrating these settings from the separate modal dialog to the normal `PropertyPanel` in order to enable live feedback on the changes in the editor and reduce the friction to play around with `Emitter` settings. 
Alternatively, there should be at least a preview of the emitter in the modal dialog.

### PR DESCRIPTION
**Pull request by nightm4re94**
This resolves #298 .
Instead of the entirely broken popup panel for Emitter manipulation, I introduced a hierarchy of PropertyPanels to modify Emitters on the fly and with more comprehensible controls.
Highlights:

- Added a tabbed PropertyPanel to manipulate Emitters
- Enhanced MapObjectInspector.
- Introduced default values for EmitterData.
- Introduced AntiAliasing for particles.
- Introduced Rotation for all particles (#345).
- Introduced Animation for SpriteParticles.
- Streamlined ParticleTypes and introduced generic PolygonParticles.
- Fixed particle bounding boxes.
- Fixed emitter spawn rate
- Renamed some Particle parameters.
- Deprecated Spritesheet Emitters and Animation Emitters (functionality now available for all custom emitters).

### CODE REVIEW

**Comment by steffen-wilke** [comment]
> Deprecated Spritesheet Emitters and Animation Emitters (functionality now available for all custom emitters).

Please consider removing these and provide a description on how to migrate/ how the new API looks like. I'd like to add this to the Release notes.

The goal is to not have any deprecated API as long as we're in alpha state. Once we reach the first stable version, changing the existing API will become more gracefully. And our version strategy will ensure a certain consistency within the API.

**Comment by steffen-wilke** [comment]
Please consider resolving this duplicated Code:

https://sonarcloud.io/component_measures?id=de.gurkenlabs%3Alitiengine&metric=new_duplicated_lines_density&view=list

https://sonarcloud.io/component_measures?id=de.gurkenlabs%3Alitiengine&metric=new_duplicated_lines_density&selected=de.gurkenlabs%3Alitiengine%3Autiliti%2Fsrc%2Fde%2Fgurkenlabs%2Futiliti%2Fswing%2Fpanels%2FEmitterTextPanel.java

Maybe a parent class for `EmitterTextPanel` and `EmitterColorPanel` would be appropriate.

**Comment by steffen-wilke** [comment]
The recent changes also introduced lots of new `CODE_SMELLS`. Please attempt to resolve them where possible.

https://sonarcloud.io/project/issues?id=de.gurkenlabs%3Alitiengine&resolved=false&sinceLeakPeriod=true&types=CODE_SMELL

**Comment by nightm4re94** [comment]
> > Deprecated Spritesheet Emitters and Animation Emitters (functionality now available for all custom emitters).
> 
> Please consider removing these and provide a description on how to migrate/ how the new API looks like. I'd like to add this to the Release notes.
> 
> The goal is to not have any deprecated API as long as we're in alpha state. Once we reach the first stable version, changing the existing API will become more gracefully. And our version strategy will ensure a certain consistency within the API. 

I am very aware of this 👌

**Pull request merged**
