### PR TITLE
Resolve issue from PR #397 and overall improve tests

### PR DESCRIPTION
**Pull request by jluech**
- Resolved issue from [PR #397](https://github.com/gurkenlabs/litiengine/pull/397#issuecomment-832167001):
	- added extensive tests for `shapeIntersects()` method,
	- added different behavior for `Line2D` (a line does not have a geometric area),
	- switch methods to agreed solution mentioned in comments
- Overall improved tests and increased coverage

### CODE REVIEW

**Comment by jluech** [comment]
```
[20:50] Janik Lüchinger
    
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sonarqube'.
> You're not authorized to run analysis. Please contact the project administrator.
```
Is that an issue we should fix or is it a configuration error on your side?

**Comment by nightm4re94** [comment]
> 
> 
> ```
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':sonarqube'.
> > You're not authorized to run analysis. Please contact the project administrator.
> ```
> 
> Is that an issue we should fix or is it a configuration error on your side?

My bad! We migrated our build pipeline from travis to GitHub actions this weekend. Need to exclude the sonar scan for builds outside the main repo again.

**Comment by jluech** [comment]
> 
> 
> > ```
> > FAILURE: Build failed with an exception.
> > 
> > * What went wrong:
> > Execution failed for task ':sonarqube'.
> > > You're not authorized to run analysis. Please contact the project administrator.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is that an issue we should fix or is it a configuration error on your side?
> 
> My bad! We migrated our build pipeline from travis to GitHub actions this weekend. Need to exclude the sonar scan for builds outside the main repo again.

any news on that?

**Comment by nightm4re94** [comment]
I've added a condition on the master branch that skips sonar scans in forks. please try merging and we'll see if it works as intended :)

**Comment by jluech** [comment]
I triggered a rerun of the checks, now "Gradle SonarQube Scan" is skipped as intended and all checks pass. I cannot merge without write access to the repository though ;)

**Review by nightm4re94 — APPROVED** [review]
I'm sorry it took me this long to review. We're very grateful for your work, thank you!

**Pull request merged**
