### PR TITLE
Build overhaul

### PR DESCRIPTION
**Pull request by weisJ**
WIP overhaul of the build scripts

### CODE REVIEW

**Comment by weisJ** [comment]
Things I am not sure about: I have the `com.stehno.natives` plugin applied but currently don't use it actively. Tests seem to run fine, so if this introduces any issue they ought to be packaging related.

**Comment by weisJ** [comment]
`TileDataTest#testEncode` fails with java 16. It runs fine on java 11. There probably has been a change in the compression algorithm?

**Comment by weisJ** [comment]
`TileDataTest#testEncode` fails becuase in java 16 the implementation of `GzipOutputStream` uses a different value for the OS flag in the gzip header:
https://github.com/openjdk/jdk/commit/e5866aa7560e1a6077a90a5902ec61de76922440#diff-2648e7465e30b0816f2219556cbc8d7085e876d00365f742c7d0d8e14636fd0f

**Comment by nightm4re94** [comment]
Damn, I hadn't thought about that. I'm sorry @weisJ, but I'll have to revert because the repo chronology is now a mess. If possible, try to split up your changes into smaller units for us to process - PRs this large are a nightmare 😏 to review.

**Comment by Gamebuster19901** [comment]
Yeah I'd recommend reverting by force pushing a branch that has been hard reset to commit 1ab49e67edf67242f1e1e6a67b54f36dd9b09c7e so the repo size isn't bloated due to the duplicate files that have to be stored in the repository.

**Comment by weisJ** [comment]
The history issue is a rather sad technical limitation of GitHub (partly git). It is possible to view the complete git history of a file using `git log —follow` however GitHub doesn’t do this currently: https://github.com/isaacs/github/issues/900

There is no way to change the directory structure while keeping the visible gitHub history and not modify the git history (as it would technically be possible to rebase all commits on top of the file move commits).

**Comment by Gamebuster19901** [comment]
Regardless, I'm sure there's a way to improve the build system without moving the entirety of the `src` folder. That folder doesn't really have anything to do with the build system in the first place.

**Comment by nightm4re94** [comment]
I wouldn't expect GitHub to address this long-standing issue soon, and for the time being, we value the accessibility of our past >3000 commits more than a simplified and more convenient build infrastructure. 
As I said, this PR changes a lot of different things that are not necessarily related - therefore it would be possible to address each of these issues in separate, atomic PRs.

**Comment by Gamebuster19901** [comment]
Just so you know I have a branch in the correct state if you decide to force push: https://github.com/Gamebuster19901/litiengine/tree/master2

Note that if you force push  https://github.com/Gamebuster19901/litiengine/tree/master2 into https://github.com/gurkenlabs/litiengine, you **_will break any branches that have commits that were in this PR_**, but I don't think anyone besides myself, weisJ, and you guys would have a branch with those commits yet.

A simple revert commit won't be enough to fully undo this, because git blame will still be messed up: https://github.com/Gamebuster19901/litiengine/blame/revert-412-build_overhaul/src/de/gurkenlabs/litiengine/Game.java

However it's better than nothing if you decide to forgo force pushing.

**Comment by weisJ** [comment]
To force push to master the branch protection first needs to be turned off

**Pull request merged**
