### PR TITLE
Add Tweening framework.

### PR DESCRIPTION
**Pull request by nightm4re94**
This PR adds a package for interpolating values over time, offering predefined [Easing functions defined by Robert Penner](http://robertpenner.com/easing/) as well as the possibility to define custom mathematical tweening equations. If an object implements the `Tweenable` interface, it can override the `getTweenValues` and `setTweenValues` methods to define which attributes will be modified.
Current examples for Tweenables are `Entities`(position, dimensions, angle, hitpoints, collision dimensions, velocity) and `GuiComponent`s (position, dimensions, text angle), as well as `SoundPlayback`s (volume).
Each game has one instance of a `TweenEngine` which operates as a manager for all registered `Tween` instances and applies their `TweenEquation` with each update. It can be retrieved using `Game.tweens()`. 
Tweens can be stopped, resumed, and reset, as the examples below show:

``` java
GuiComponent comp = new GuiComponent();

// Start a Tween or restart it, if there is already a Tween. In this case, the width and height of the GuiComponent will be decreased by 10 over the course of 500 milliseconds, using an elastic easing function.
Game.tweens().begin(comp, TweenType.SIZE_BOTH, 500).targetRelative(-10, -10).ease(TweenFunction.ELASTIC_OUT);

// Stop a Tween
Game.tweens().stop(comp, TweenType.SIZE_BOTH);

// Resume a Tween
Game.tweens().resume(comp, TweenType.SIZE_BOTH);

// Reset the component's width and height to how they were before tweening
Game.tweens().reset(comp, TweenType.SIZE_BOTH);
```

Apart from the Tweening framework, this PR implements the following changes:
- Add a listener to receive events when a key is released
- Add setters for row height and column with in ImageComponentLists
- Remove distinction between Particle color alpha and opacity. (Fix flickering particle opacity when fading.)

### CODE REVIEW

**Comment by steffen-wilke** [comment]
lgtm

**Review by steffen-wilke — APPROVED** [review]
- Document changes on `Particle` and `IKeyboard`.
- Adjust licensing and remove "unnecessary" easing functions.

TODO:
- Loopable Tweens
- Missing events of tweens
- Possibility to determine whether a `TweenType` is supported by a `Tweenable`

**Comment by nightm4re94** [comment]
Last change adressed these remarks:
  * Possibility to determine whether a TweenType is supported by a Tweenable
  * Document changes on Particle and IKeyboard.
  * Adjust licensing and remove "unneccessary" easing functions.

**Comment by TheRamenChef** [comment]
It seems I came just a few hours too late to offer my feedback on this PR.

First of all, the complete list of `VolumeControl` instances should *not* be exposed publicly, nor should it be accessed anywhere other than the `updateVolume` method, because a method iterating over it does not know what any of them are supposed to represent. And the list is grossly misused by the various `fade` methods, which currently fade out every volume control attached to the playback instance. They *should* either create an independent volume control for it or use the master volume control (as the `fade` method seems to be mainly concerning the master volume).

On the subject of the `fade` method also, the original `fadeMusic` method was supposed to make the music fade *out*, and would stop the playback as soon as the volume reached zero. It no longer does this in the current version.

Second, it seems that `TweenType` and `Tweenable` could be replaced with interfaces to get and set tweened values (or just use `DoubleSupplier` and `DoubleConsumer`), possibly with an additional class to manage several at once.

Third, the `TweenFunction` enum appears to exist only as a wrapper for a `TweenEquation` that can't be instantiated, and removing it in favor of the underlying `TweenFunction`s would make the API simpler and more flexible.

I'm sure I could find more ways to improve this API, but I haven't looked at it all that closely yet.

**Comment by nightm4re94** [comment]
You're very welcome to enhance this, it's been a bit of a rushed PR as we wanted to have a common ground for our project this month without overcomplicating the branching of the engine.
Some further changes have already been proposed in #363, please track your proposals there.

**Pull request merged**
